---
title: Assessment of Labs
---


Labs are assessed on a 4-part rubric similar to the EMRF rubric of [Stutzman and Race](http://miss-serwy.weebly.com/uploads/1/2/1/6/12161802/emrf_rubric_1.pdf):[This particular scale is very close to the scale [used by Peter-Michael Osera](https://osera.cs.grinnell.edu/csc208/syllabus/#projects) at Grinnell College.]{.aside} 

A lab report obtains the highest grade for which it meets **all** of the requirements. 

**Excellent** (**E**): 

- The lab includes a complete contributions statement describing the contributions of any collaborators, as well as external sources such as websites or ChatGPT. 
- The lab exhibits complete understanding of the material. 
- The lab has at worst, a few minor design errors or surface-level writing issues. 
- **Mathematics**
    - Included typed mathematics is **fully correct**, including steps and final result. 
    - Mathematics is correctly typed when required. 
    - Mathematical work has all steps clearly justified as demonstrated in the solutions. 
        - Each stage of a calculation is justified by an appeal to a known result, identity, or formula. 
        - Proofs are correct and justify their steps. 
- All required pictures from the board are included. 
- All coding experiments run and produce correct outputs.  

**Meets Expectations** (**M**):

- The lab exhibits complete understanding of the material. 
- The lab includes a complete contributions statement describing the contributions of any collaborators, as well as external sources such as websites or ChatGPT. 
- The lab has some minor errors of correctness, design, or writing. Fixing these errors would demonstrate improved understanding of the material. 
- **Mathematics**
    - Included typed mathematics is **fully correct**, including steps and final result. 
    - Mathematics is mostly correctly typed, possibly with a few minor typing errors. 
    - Mathematical calculations have some of their steps justified as demonstrated in the solutions. 
        - Most stages of calculations are justified by an appeal to a known result, identity, or formula. 
        - Proofs usually justify their steps. 
- All coding experiments run and produce outputs which are close to expected. 

**Needs Revision** (**R**): 

- The lab exhibits one or more significant misunderstandings of the material, or many minor errors. 
- Coding experiments do not run or produce substantially incorrect output. 
- **Mathematics**
    - Included typed mathematics is **incorrect in at least one problem**, including steps or final result. 
    - Mathematics is correctly typed in at least some cases, with many major errors. 
    - Most or all mathematical calculations and proofs do not include a justification of their steps. 
- The contributions statement is partial or missing. 

**Not Completed** (**N**): 

- Not completed to a degree sufficient to demonstrate understanding of the material. 
