
---
title: Masks Are Required in CSCI 0200
---

The Computer Science Department policy states that: 

> We in the Computer Science department value a safe learning and working environment for all. While we can't eliminate the risks associated with COVID-19, [evidence suggests](https://www.pnas.org/doi/full/10.1073/pnas.2014564118) that widespread masking can significantly reduce the transmission and severity of disease. In order to protect the health of our community, the CS department recommends that students and faculty wear masks in CS learning spaces, including classrooms, office hours, and public areas. We acknowledge the College policy gives instructors the final say over classroom masking requirements, and expect all students to respect instructors' stated policies in each course.

In alignment with this policy: 

- Masks are required during scheduled class periods in Weeks 1 and 2 and after Thanksgiving break. 
- Masks are encouraged during Student Hours and Peer Help. 
- Masks are required during private meetings in my office. 

During the first week of class, I will stock masks that I will offer you in case you forget yours. In the second week of class, you will be responsible for bringing your own masks. If you arrive in class without one, I'll ask you to leave class and come back once you have obtained a mask. 