---
title: "Implication, Inverse, Converse, and Contrapositive"
---

*As we enter the second week, we are going to pick up the pace on introducing videos, readings, and warmup problems.*

# Videos (~35 mins)

- [Tautologies and Contradictions](https://youtu.be/Ji2vr-9duPI?si=Ey4WlBJwNHazZs2z) (3:40)
- [3 Ways to Show a Logical Equivalence](https://youtu.be/93CxSLi89Ok?si=bXZ9oTi-6f4-RHAD) (5:28)
- [Conditional Statements: if *p* then *q*](https://youtu.be/F3544ZyO-eU?si=Z3_-A46qah_bu6rg) (7:09)
- [Vacuously True Statements](https://youtu.be/AQ0f4rsbsrQ?si=NxAbYKVbjvmh4ktJ) (2:00)
- [Negating a Conditional Statement](https://youtu.be/j7qVcc6X8g4?si=G8UU1SJZT236nzss) (2:51)
- [Contrapositive of a Conditional Statement](https://youtu.be/h83bzYAfgrM?si=qqO_wpX-7R9oqJch) (4:59)
- [The Converse and Inverse of a Conditional Statement](https://youtu.be/BNhp6LXncI0?si=nieKCEA0Z2BWHIzX) (5:04)
- [Biconditional Statements | "if and only if"](https://youtu.be/oHijygNdx_8?si=Txppresck906nTBm) (2:53)

# Reading (40 mins)
 
- [DMOI 3.1](https://discrete.openmathbooks.org/dmoi3/sec_propositional.html) through Example 3.1.5. 
<!-- - [Privilege is the Inverse of Discrimination](https://medium.com/@davestagner/privilege-is-the-inverse-of-discrimination-334d0c7f4fbd) (***Note**: I think this is a helpful piece, but be aware that it uses problematically simple binaries in race and gender.*) -->
 
## Optional Reading

- [BOP 2.3-2.6](https://www.people.vcu.edu/~rhammack/BookOfProof/Main.pdf#page=54)
 
# Warmup Problems (~30 mins) 

*Please complete these problems "by hand," without typing. Pencil/pen and paper is best practice for the quiz, but using a stylus with a tablet is also fine. Then, scan/photograph or otherwise produce an image of your solutions and upload them to Canvas.*

## Problem 1
 
{{< include ../../../content/problems/logic/implications-2.qmd >}}

## Problem 2

{{< include ../../../content/problems/logic/implications-1.qmd >}}

## Problem 3
  
{{< include ../../../content/problems/logic/implications-3.qmd >}}